version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "button-timestamp-recorder"
s3_prefix = "button-timestamp-recorder"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
