version = 0.1

[default]
[default.global.parameters]
stack_name = "dsql-version-stack"

[default.build.parameters]
use_container = true
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
region = "ap-northeast-1"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "dsql-version-stack"
image_repositories = []

[default.local_start_api.parameters]
port = 3000
host = "127.0.0.1"